### ISSUE TITLE
" npm run dev " not working in windows system

### ISSUE THREAD

**Issue by bharathmit** [shopizer-ecommerce/shopizer-shop-reactjs#1]
Hi team,

I am new to react js , while I setup the code and run the script getting below error in  npm run dev script.

![image](https://user-images.githubusercontent.com/6636257/131381803-bfd2a15f-06f1-484d-964f-cd39e2fe0e21.png)

**Comment by SimonHasak** [comment]
Windows terminal and Unix (Mac/linux) doesn`t have the same commands. What you can try is to install Windows Subsystem for Linux (wsl2 is the most new version) or cygwin for kind of enabling unix commands in windows. Check definitions by yourself. I was trying different project with cygwin but there were others problems regarding OS so I used virtual machine. Or you can try Visual Studio Code. My coworkers are using it and are saying it has shell terminal but wasn`t working for me also.

**Comment by bharathmit** [comment]
Now able to run in windows,

chmod +x ./env.sh && ./env.sh && cp env-config.js ./public/ && react-scripts start


step 1: run the env.sh file from cmd or powershell - It will generate  env-config.js root directory 
step 2:  move the env-config.js into public folder
step 3: run --> react-scripts start ----> it will run the reactjs app
