### ISSUE TITLE
Home Page not opening while hitting localhost:3000

### ISSUE THREAD

**Issue by DxcGSS** [shopizer-ecommerce/shopizer-shop-reactjs#7]
Home Page not opening while hitting localhost:3000
<img width="951" alt="ErrorPage" src="https://user-images.githubusercontent.com/47327402/148650335-3e16297d-d831-4adf-b4fd-ad32c95ccd07.PNG">

**Comment by guoxiaoxu** [comment]
https://github.com/shopizer-ecommerce/shopizer-shop-reactjs/blob/main/.env
 .env --> APP_BASE_URL=http://localhost:8080

npm run start

**Comment by libaoqian** [comment]
I get the same error
![image](https://user-images.githubusercontent.com/16265310/150757837-5dc4fd61-a41b-4c40-a07b-2a499ffaec9b.png)

**Comment by shopizer-ecommerce** [comment]
It is looking for env_config.js
This file in in the root directory normally constructed for docker but was absent because of a .gitignore rule

Pull and retry :-)

Thanks
